repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: pretty-format-json
        args: ['--no-sort-keys']

  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest version of Black
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Latest version
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Latest version
    hooks:
      - id: isort

  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.6.9
    hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ['--skip', 'B101,B110,B603']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [sqlalchemy-stubs, types-ujson]
        args: ['--ignore-missing-imports']
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade
